/**
 * Safe Share & Export Module (LINE Share, Image Card, PDF Print)
 * ワンタップ安全共有、プライバシー防衛済LINEフォーマット、カード画像生成、PDF印刷モジュール
 */

const Exporter = (function () {

  /**
   * LINE共有用テキスト生成 & クリップボードコピー
   */
  function shareToLine(journal) {
    if (!journal) return;

    // プライバシーフィルターを確実に適用
    const safeText = PrivacyFilter.sanitizeText(journal.cleanedContent || journal.rawContent, 'strict').maskedText;

    const shareBody = `
⚾ 【AI野球ノート】${journal.date} (${journal.category})
----------------------------------
ポジション: ${journal.position}
コンディション: ${journal.condition}

【AI清書ノート】
${safeText}

【AI評価スコア】
・打撃: ${journal.scores ? journal.scores.batting : 80}点
・守備: ${journal.scores ? journal.scores.defense : 70}点
・メンタル: ${journal.scores ? journal.scores.mental : 75}点

【明日のAIアドバイス】
${journal.immediateAdvice || '基礎練習を意識して取り組みましょう！'}
----------------------------------
#AI野球ノート #BaseballNote #安全防衛共有
    `.trim();

    if (navigator.clipboard) {
      navigator.clipboard.writeText(shareBody).then(() => {
        alert("✅ プライバシー防衛済みのノート本文をコピーしました！LINEやグループチャットにそのまま貼り付けできます。");
      }).catch(err => {
        console.error("Clipboard copy error:", err);
        alert("コピーに失敗しました。手動でテキストを選択してください。");
      });
    } else {
      alert("お使いのブラウザはクリップボードコピーに対応していません。");
    }
  }

  /**
   * HTML Canvasを利用して美しい分析カード画像を動的生成＆ダウンロード
   */
  function exportImageCard(journal) {
    if (!journal) return;

    const canvas = document.createElement('canvas');
    canvas.width = 600;
    canvas.height = 750;
    const ctx = canvas.getContext('2d');

    // 背景グラデーション
    const gradient = ctx.createLinearGradient(0, 0, 600, 750);
    gradient.addColorStop(0, '#0B0F19');
    gradient.addColorStop(0.5, '#161E2E');
    gradient.addColorStop(1, '#0F172A');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 600, 750);

    // ネオン枠線
    ctx.strokeStyle = '#00F2FE';
    ctx.lineWidth = 4;
    ctx.strokeRect(15, 15, 570, 720);

    // タイトル
    ctx.fillStyle = '#00F2FE';
    ctx.font = 'bold 26px "Noto Sans JP", sans-serif';
    ctx.fillText('⚾ AI野球ノート - 分析レポート', 40, 65);

    // 日付・カテゴリ
    ctx.fillStyle = '#9CA3AF';
    ctx.font = '16px "Noto Sans JP", sans-serif';
    ctx.fillText(`${journal.date} | ${journal.category} | ${journal.position}`, 40, 100);

    // セパレータ
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 120);
    ctx.lineTo(560, 120);
    ctx.stroke();

    // AI清書本文 (折り返し描画)
    ctx.fillStyle = '#F3F4F6';
    ctx.font = '16px "Noto Sans JP", sans-serif';
    
    const safeText = PrivacyFilter.sanitizeText(journal.cleanedContent || journal.rawContent, 'strict').maskedText;
    const lines = safeText.split('\n');
    let curY = 160;

    lines.slice(0, 8).forEach(line => {
      ctx.fillText(line.substring(0, 32), 40, curY);
      curY += 28;
    });

    // スコアボックス背景
    ctx.fillStyle = 'rgba(0, 242, 254, 0.08)';
    ctx.fillRect(40, curY + 20, 520, 100);
    ctx.strokeStyle = 'rgba(0, 242, 254, 0.3)';
    ctx.strokeRect(40, curY + 20, 520, 100);

    ctx.fillStyle = '#00F2FE';
    ctx.font = 'bold 18px "Noto Sans JP", sans-serif';
    ctx.fillText('【AIパフォーマンス評価】', 60, curY + 55);

    const bScore = journal.scores ? journal.scores.batting : 80;
    const dScore = journal.scores ? journal.scores.defense : 70;
    const mScore = journal.scores ? journal.scores.mental : 75;

    ctx.fillStyle = '#FFF';
    ctx.font = 'bold 20px "Noto Sans JP", sans-serif';
    ctx.fillText(`打撃: ${bScore}点  |  守備: ${dScore}点  |  メンタル: ${mScore}点`, 60, curY + 90);

    // フッター
    ctx.fillStyle = '#64748B';
    ctx.font = '13px "Noto Sans JP", sans-serif';
    ctx.fillText('Generated by Smart Baseball AI Coach (戦術・個人情報保護済)', 40, 710);

    // 画像ダウンロード
    const dataUrl = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.download = `baseball_note_${journal.date}.png`;
    link.href = dataUrl;
    link.click();
  }

  /**
   * PDF印刷ウィンドウを起動
   */
  function printPDF() {
    window.print();
  }

  return {
    shareToLine,
    exportImageCard,
    printPDF
  };

})();

window.Exporter = Exporter;
